config/routes.rb
Rails.application.routes.draw do
  resources :projects
  devise_for :users
  get 'home/index'

  resources :tasks
  root 'projects#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  #validates :project_id, presence: true :project
  belongs_to :project
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!


  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new

  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    @task.user = current_user
    @task.project = $project

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:title, :description, :due_date, :status)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form_group">
    <%= form.label :title, for: :task_title %>
    <%= form.text_field :title, id: :task_title, class: "form-control" %>
  </div>

  <div class="field form_group">
    <%= form.label :description, for: :task_description %>
    <%= form.text_area :description, id: :task_description, class: "form-control" %>
  </div>

  <div class="field form_group">
    <%= form.label :due_date, for: :task_due_date %>
    <%= form.date_select :due_date, id: :task_due_date, :class => "form-control" %>
  </div>

  <div class="field form_group">
    <%= form.label :status, for: :status %>
    <%= form.number_field :status, id: :task_status, :class => "form-control" %>
  </div>

  <br>

  <div class="actions form_group">
    <%= form.submit "Submit", :class => "btn btn-primary"%>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<div class="page-header">
  <h1>Editing Task</h1>
</div>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task, class: "btn btn-primary", role: "button" %> |
<%= link_to 'Back', tasks_path, class: "btn btn-info", role: "button" %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>
<!-- Page Content -->
<div class="container">

  <div class="page-header">
    <h1 class="my-4">Tasks</h1>
  </div>

  <div class="row">
    <% @tasks.each do |task| %>
      <div class="col-lg-3 col-md-4 col-sm-6 mb-4">
        <div class="card h-100">
          <div class="card-body">
            <h4 class="card-title">
              <a href="#"><%= task.title %></a>
            </h4>
            <p class="card-text"><%= task.description %></p>
            <p class="card-text"><small>Due date: </small><%= task.due_date %></p>
            <p class="card-text"><small>Status: </small><%= task.status %></p>
            <%= link_to 'Show', task,  class: "btn btn-primary", role: "button" %> 
            <%= link_to 'Edit', edit_task_path(task),  class: "btn btn-info", role: "button" %>
            <%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' },  class: "btn btn-danger", role: "button" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<br>

<%= link_to 'New Task', new_task_path, class: "btn btn-info", role: "button" %>

app/views/tasks/new.html.erb
<div class="page-header">
    <h1>New Task</h1>
</div>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path, class: "btn btn-info", role: "button" %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>
<div class="col-lg-3 col-md-4 col-sm-6 mb-4">
  <div class="card h-100">
    <div class="card-body">
      <h4 class="card-title">
        <strong>Title:</strong>
        <%= @task.title %>
      </h4>
      <p class="card-text">
        <strong>Description:</strong>
        <%= @task.description %>
      </p class="card-text">

      <p class="card-text">
        <strong>Due date:</strong>
        <%= @task.due_date %>
      </p>

      <p class="card-text">
        <strong>Status:</strong>
        <%= @task.status %>
      </p>
      <%= link_to 'Edit', edit_task_path(@task), class: "btn btn-primary", role: "button"  %> |
      <%= link_to 'Back', tasks_path, class: "btn btn-info", role: "button"  %>
    </div>
  </div>
</div>