config/routes.rb
Rails.application.routes.draw do
  resources :projects
  devise_for :users
  get 'home/index'

  resources :tasks
  root 'projects#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
  has_and_belongs_to_many :user
  has_many :tasks
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /projects
  # GET /projects.json
  def index
    if current_user.is_admin?
      @projects = Project.all
    else
      @projects = current_user.projects
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @task = Task.new
    $project = @project
    #@task.project = @project
    #@task.project_id = @project
    #@task.user = current_user

    @project.user += [current_user]
    @project.tasks = Task.where(project_id: @project)
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    Task.where(project_id: @project.id).destroy_all
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :description, :user_id)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form_group">
    <%= form.label :title, for: :title %>
    <%= form.text_field :title, id: :project_title, class: "form-control" %>
  </div>

  <div class="field form_group">
    <%= form.label :description, for: :description %>
    <%= form.text_area :description, id: :project_description, class: "form-control" %>
  </div>

  <br>

  <div class="actions">
    <%= form.submit "Submit", :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<div class="page-header">
  <h1>Editing Project</h1>
</div>
<%= render 'form', project: @project %>

<%= link_to 'Show', @project, class: "btn btn-primary", role: "button" %> |
<%= link_to 'Back', projects_path, class: "btn btn-info", role: "button" %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="page-header">
    <h1 class="my-4">Projects</h1>
  </div>
  
  <% @projects.each do |project| %>    
    <!-- Row -->
      <div class="row">
        <div class="col-md-7">
          <a href="#">
          <%= image_tag(Prototipo.getImage(project.id), class:"img-fluid rounded mb-3 mb-md-0", size: 400)%>
          </a>
        </div>
        <div class="col-md-5">
          <h3><%= project.title %></h3>
          <p><%= project.description %></p>
          <p><small>Users: </small>

          <% project.user.each do |u| %>
            <%= u.email %>
            <% end %>


          <%= link_to 'Show', project,  class: "btn btn-primary", role: "button" %>
          <%= link_to 'Edit', edit_project_path(project),  class: "btn btn-info", role: "button" %>
          <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' },  class: "btn btn-danger", role: "button" %>
        </div>
      </div>
      <!-- /.row -->

      <hr>
  <% end %>
  </div>

  <br>

  <%= link_to 'New Project', new_project_path,  class: "btn btn-primary", role: "button" %>
</div>

app/views/projects/new.html.erb
<div class="page-header">
  <h1>New Project</h1>
</div>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path, class: "btn btn-info", role: "button" %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
<div class="col-lg-12 col-md-12 col-sm-12 mb-12">
  <div class="card h-100">
    <div class="card-body">
      <h1 class="card-title">
        <strong>Title:</strong>
        <%= @project.title %>
      </h1>
      <p class="card-text">
        <strong>Description:</strong>
        <%= @project.description %>
      </p>
    </div>
    <div class="card-body">
      <h2 class="card-title">Users</h2>
      <ul>
        <% @project.user.each do |user|%>
          <li>
            <p class="card-text"><%=user.email%></p>
          </li>
        <%end%>
      </ul>
    </div>
  </div>
</div>
</div>
<br>
<h2 class="card-title">Tasks</h2>
<div class="row">
  <% @project.tasks.each do |task|%>
    <div class="col-lg-3 col-md-4 col-sm-6 mb-4">
      <div class="card h-100">
        <div class="card-body">
          <h3 class="card-title">
            <strong>Title:</strong>
            <%=task.title%>
          </h3>
          <p class="card-text">
            <strong>Description:</strong>
            <%= task.description %>
          </p>
          <p class="card-text">
            <strong>Due date:</strong>
            <%= task.due_date %>
          </p>
          <%= link_to 'Edit', edit_task_path(task), class: "btn btn-primary", role: "button"  %>
          <%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' },  class: "btn btn-danger", role: "button" %> 
        </div>
      </div>
    </div>
  <%end%>
</div>
<p>
  <%= render './tasks/form', project: @project, task: @task %>
</p>



<%= link_to 'Edit', edit_project_path(@project), class: "btn btn-info", role: "button" %> |
<%= link_to 'Back', projects_path, class: "btn btn-secondary", role: "button" %>